In [112]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

In [113]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [114]:
df.shape

(569, 33)

In [115]:
df = df.drop(columns=['id','Unnamed: 32'])

## Train, Test, Split

In [116]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [117]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
360,12.540,18.07,79.42,491.9,0.07436,0.02650,0.001194,0.005449,0.1528,0.05185,...,13.720,20.98,86.82,585.7,0.09293,0.04327,0.003581,0.01635,0.2233,0.05521
276,11.330,14.16,71.79,396.6,0.09379,0.03872,0.001487,0.003333,0.1954,0.05821,...,12.200,18.99,77.37,458.0,0.12590,0.07348,0.004955,0.01111,0.2758,0.06386
262,17.290,22.13,114.40,947.8,0.08999,0.12730,0.096970,0.075070,0.2108,0.05464,...,20.390,27.24,137.90,1295.0,0.11340,0.28670,0.229800,0.15280,0.3067,0.07484
339,23.510,24.27,155.10,1747.0,0.10690,0.12830,0.230800,0.141000,0.1797,0.05506,...,30.670,30.73,202.40,2906.0,0.15150,0.26780,0.481900,0.20890,0.2593,0.07738
456,11.630,29.29,74.87,415.1,0.09357,0.08574,0.071600,0.020170,0.1799,0.06166,...,13.120,38.81,86.04,527.8,0.14060,0.20310,0.292300,0.06835,0.2884,0.07220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,13.880,16.16,88.37,596.6,0.07026,0.04831,0.020450,0.008507,0.1607,0.05474,...,15.510,19.97,99.66,745.3,0.08484,0.12330,0.109100,0.04537,0.2542,0.06623
45,18.650,17.60,123.70,1076.0,0.10990,0.16860,0.197400,0.100900,0.1907,0.06049,...,22.820,21.32,150.60,1567.0,0.16790,0.50900,0.734500,0.23780,0.3799,0.09185
410,11.360,17.57,72.49,399.8,0.08858,0.05313,0.027830,0.021000,0.1601,0.05913,...,13.050,36.32,85.07,521.3,0.14530,0.16220,0.181100,0.08698,0.2973,0.07745
4,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.198000,0.104300,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.400000,0.16250,0.2364,0.07678
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.086060,0.028720,0.1902,0.08980,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.143400,0.04786,0.2254,0.10840

## Scaling

In [118]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [119]:
y_train

360    B
276    B
262    M
339    M
456    B
      ..
387    B
45     M
410    B
4      M
71     B
Name: diagnosis, Length: 455, dtype: str

## Label Encoding

In [120]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [121]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0])

## Numpy arrays to tensor

In [122]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [123]:
X_train.shape

torch.Size([455, 30])

In [124]:
X_train.shape[0]

455

In [125]:
X_train

tensor([[-0.4730, -0.2979, -0.5406,  ..., -1.5055, -1.0881, -1.6147],
        [-0.8239, -1.1804, -0.8617,  ..., -1.5850, -0.2553, -1.1290],
        [ 0.9042,  0.6186,  0.9317,  ...,  0.5653,  0.2348, -0.5125],
        ...,
        [-0.8152, -0.4107, -0.8323,  ..., -0.4336,  0.0857, -0.3659],
        [ 1.7740, -1.1398,  1.8030,  ...,  0.7125, -0.8803, -0.4035],
        [-1.5319, -1.0721, -1.4089,  ..., -1.0273, -1.0547,  1.3720]],
       dtype=torch.float64)

## Main NN Class

In [126]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1, dtype=torch.float64)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

## Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 40

In [ ]:
y_train = y_train.float()

In [128]:
loss_function = nn.BCELoss()

## Training Pipeline

In [140]:
# Create model
model = MySimpleNN(X_train.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(X_train)
    y_pred = y_pred.float()


    # Loss Calculate
    loss = loss_function(y_pred, y_train.view(-1,1))
    print(f"Loss for epoch {epoch}: {loss}")

    # Clearing gradients
    optimizer.zero_grad()

    # Backward Pass
    loss.backward()

    # Parameters update
    optimizer.step()

Loss for epoch 0: 0.7043809294700623
Loss for epoch 1: 0.5355186462402344
Loss for epoch 2: 0.4468548595905304
Loss for epoch 3: 0.3921572268009186
Loss for epoch 4: 0.3544691205024719
Loss for epoch 5: 0.3265632390975952
Loss for epoch 6: 0.3048447072505951
Loss for epoch 7: 0.28731560707092285
Loss for epoch 8: 0.27277201414108276
Loss for epoch 9: 0.26044219732284546
Loss for epoch 10: 0.249807208776474
Loss for epoch 11: 0.24050375819206238
Loss for epoch 12: 0.23226964473724365
Loss for epoch 13: 0.22491009533405304
Loss for epoch 14: 0.2182771861553192
Loss for epoch 15: 0.21225619316101074
Loss for epoch 16: 0.2067568600177765
Loss for epoch 17: 0.20170676708221436
Loss for epoch 18: 0.19704723358154297
Loss for epoch 19: 0.19273002445697784
Loss for epoch 20: 0.18871518969535828
Loss for epoch 21: 0.18496912717819214
Loss for epoch 22: 0.18146352469921112
Loss for epoch 23: 0.1781741827726364
Loss for epoch 24: 0.1750803291797638
Loss for epoch 25: 0.17216403782367706
Loss for epoch 26: 0.1694096028804779
Loss for epoch 27: 0.16680334508419037
Loss for epoch 28: 0.16433316469192505
Loss for epoch 29: 0.16198837757110596
Loss for epoch 30: 0.15975938737392426
Loss for epoch 31: 0.15763771533966064
Loss for epoch 32: 0.1556156426668167
Loss for epoch 33: 0.15368624031543732
Loss for epoch 34: 0.15184323489665985
Loss for epoch 35: 0.15008090436458588
Loss for epoch 36: 0.14839401841163635
Loss for epoch 37: 0.14677779376506805
Loss for epoch 38: 0.14522784948349
Loss for epoch 39: 0.14374017715454102
Loss for epoch 40: 0.1423109769821167
Loss for epoch 41: 0.14093688130378723
Loss for epoch 42: 0.13961468636989594
Loss for epoch 43: 0.13834141194820404
Loss for epoch 44: 0.13711436092853546
Loss for epoch 45: 0.13593098521232605
Loss for epoch 46: 0.1347889006137848
Loss for epoch 47: 0.133685901761055
Loss for epoch 48: 0.1326199322938919
Loss for epoch 49: 0.1315890997648239
Loss for epoch 50: 0.13059160113334656
Loss for epoch 51: 0.12962578237056732
Loss for epoch 52: 0.12869003415107727
Loss for epoch 53: 0.127782940864563
Loss for epoch 54: 0.12690310180187225
Loss for epoch 55: 0.1260492354631424
Loss for epoch 56: 0.1252201348543167
Loss for epoch 57: 0.12441467493772507
Loss for epoch 58: 0.1236317977309227
Loss for epoch 59: 0.12287046015262604
Loss for epoch 60: 0.12212976068258286
Loss for epoch 61: 0.12140882015228271
Loss for epoch 62: 0.12070674449205399
Loss for epoch 63: 0.12002277374267578
Loss for epoch 64: 0.1193561851978302
Loss for epoch 65: 0.11870624125003815
Loss for epoch 66: 0.11807229369878769
Loss for epoch 67: 0.11745370179414749
Loss for epoch 68: 0.1168498694896698
Loss for epoch 69: 0.11626021564006805
Loss for epoch 70: 0.11568424105644226
Loss for epoch 71: 0.11512139439582825
Loss for epoch 72: 0.114571213722229
Loss for epoch 73: 0.11403323709964752
Loss for epoch 74: 0.11350703984498978
Loss for epoch 75: 0.11299217492341995
Loss for epoch 76: 0.11248825490474701
Loss for epoch 77: 0.11199493706226349
Loss for epoch 78: 0.11151181906461716
Loss for epoch 79: 0.11103858798742294
Loss for epoch 80: 0.11057489365339279
Loss for epoch 81: 0.11012043058872223
Loss for epoch 82: 0.10967490077018738
Loss for epoch 83: 0.10923802852630615
Loss for epoch 84: 0.10880953073501587
Loss for epoch 85: 0.10838914662599564
Loss for epoch 86: 0.10797662287950516
Loss for epoch 87: 0.10757173597812653
Loss for epoch 88: 0.10717424005270004
Loss for epoch 89: 0.10678393393754959
Loss for epoch 90: 0.10640057921409607
Loss for epoch 91: 0.10602398216724396
Loss for epoch 92: 0.10565397888422012
Loss for epoch 93: 0.10529032349586487
Loss for epoch 94: 0.10493288189172745
Loss for epoch 95: 0.10458146780729294
Loss for epoch 96: 0.1042359247803688
Loss for epoch 97: 0.10389607399702072
Loss for epoch 98: 0.10356178134679794
Loss for epoch 99: 0.10323289036750793

In [142]:
with torch.no_grad():
    y_test_pred = model(X_test)
    y_pred = (y_test_pred > 0.9).float()
    accuracy = (y_pred == y_test).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5789473652839661