In [38]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

In [39]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [40]:
df.shape

(569, 33)

In [41]:
df = df.drop(columns=['id','Unnamed: 32'])

## Train, Test, Split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [43]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
452,12.000,28.23,76.77,442.5,0.08437,0.06450,0.04055,0.019450,0.1615,0.06104,...,13.090,37.88,85.07,523.7,0.1208,0.1856,0.18110,0.07116,0.2447,0.08194
349,11.950,14.96,77.23,426.7,0.11580,0.12060,0.01171,0.017870,0.2459,0.06581,...,12.810,17.72,83.09,496.2,0.1293,0.1885,0.03122,0.04766,0.3124,0.07590
46,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,0.1769,0.06503,...,8.964,21.96,57.26,242.2,0.1297,0.1357,0.06880,0.02564,0.3105,0.07409
527,12.340,12.27,78.94,468.5,0.09003,0.06307,0.02958,0.026470,0.1689,0.05808,...,13.610,19.27,87.22,564.9,0.1292,0.2074,0.17910,0.10700,0.3110,0.07592
534,10.960,17.62,70.79,365.6,0.09687,0.09752,0.05263,0.027880,0.1619,0.06408,...,11.620,26.51,76.43,407.5,0.1428,0.2510,0.21230,0.09861,0.2289,0.08278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,12.760,13.37,82.29,504.1,0.08794,0.07948,0.04052,0.025480,0.1601,0.06140,...,14.190,16.40,92.04,618.8,0.1194,0.2208,0.17690,0.08411,0.2564,0.08253
151,8.219,20.70,53.27,203.9,0.09405,0.13050,0.13210,0.021680,0.2222,0.08261,...,9.092,29.72,58.08,249.8,0.1630,0.4310,0.53810,0.07879,0.3322,0.14860
77,18.050,16.15,120.20,1006.0,0.10650,0.21460,0.16840,0.108000,0.2152,0.06673,...,22.390,18.91,150.10,1610.0,0.1478,0.5634,0.37860,0.21020,0.3751,0.11080
235,14.030,21.25,89.79,603.4,0.09070,0.06945,0.01462,0.018960,0.1517,0.05835,...,15.330,30.28,98.27,715.5,0.1287,0.1513,0.06231,0.07963,0.2226,0.07617
145,11.900,14.65,78.11,432.8,0.11520,0.12960,0.03710,0.030030,0.1995,0.07839,...,13.150,16.51,86.26,509.6,0.1424,0.2517,0.09420,0.06042,0.2727,0.10360

## Scaling

In [44]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
y_train

452    B
349    B
46     B
527    B
534    B
      ..
312    B
151    B
77     M
235    B
145    B
Name: diagnosis, Length: 455, dtype: str

## Label Encoding

In [46]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [47]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0])

## Numpy arrays to tensor

In [48]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [49]:
X_train.shape

torch.Size([455, 30])

In [50]:
X_train.shape[0]

455

In [51]:
X_train

tensor([[-0.5884,  2.1243, -0.6084,  ..., -0.6390, -0.7379, -0.1262],
        [-0.6023, -0.9831, -0.5899,  ..., -0.9902,  0.3705, -0.4549],
        [-1.6467, -0.5429, -1.6175,  ..., -1.3193,  0.3394, -0.5533],
        ...,
        [ 1.0947, -0.7044,  1.1403,  ...,  1.4391,  1.3971,  1.4441],
        [-0.0236,  0.4898, -0.0842,  ..., -0.5124, -1.0998, -0.4402],
        [-0.6162, -1.0557, -0.5545,  ..., -0.7995, -0.2795,  1.0523]],
       dtype=torch.float64)

## Main NN Class

In [52]:
class MySimpleNN:
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y_train * torch.log(y_pred) + (1-y_train) * torch.log(1-y_pred)).mean()
        return loss

## Important Parameters

In [53]:
learning_rate = 0.1
epochs = 40

## Training Pipeline

In [60]:
# Create model
model = MySimpleNN(X=X_train)

# Define loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(X_train)


    # Loss Calculate
    loss = model.loss_function(y=y_train, y_pred=y_pred)
    print(f"Loss for epoch {epoch}: {loss}")

    # Backward Pass
    loss.backward()


    # Parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Clearing gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

Loss for epoch 0: 3.868810347633062
Loss for epoch 1: 3.758596458137161
Loss for epoch 2: 3.6420922122625536
Loss for epoch 3: 3.519576919498479
Loss for epoch 4: 3.389991495141053
Loss for epoch 5: 3.2567983191696896
Loss for epoch 6: 3.121427395750675
Loss for epoch 7: 2.978261608229373
Loss for epoch 8: 2.8324699698069304
Loss for epoch 9: 2.6850568104998698
Loss for epoch 10: 2.531358765740944
Loss for epoch 11: 2.3740284658601722
Loss for epoch 12: 2.2125024597857874
Loss for epoch 13: 2.0484514512856213
Loss for epoch 14: 1.8835297688314407
Loss for epoch 15: 1.7213314420130617
Loss for epoch 16: 1.5631777981641073
Loss for epoch 17: 1.4103701509619686
Loss for epoch 18: 1.2721921762207
Loss for epoch 19: 1.1506650730822112
Loss for epoch 20: 1.0472756206747533
Loss for epoch 21: 0.9626606788330992
Loss for epoch 22: 0.8963257870310847
Loss for epoch 23: 0.8465542469603662
Loss for epoch 24: 0.8106420792136088
Loss for epoch 25: 0.7854100737054838
Loss for epoch 26: 0.7677841271231988
Loss for epoch 27: 0.7552302650718333
Loss for epoch 28: 0.7459248467060063
Loss for epoch 29: 0.7386849300157997
Loss for epoch 30: 0.7327911366865126
Loss for epoch 31: 0.7278175468786195
Loss for epoch 32: 0.7235106823141694
Loss for epoch 33: 0.7197148848974558
Loss for epoch 34: 0.7163295386202446
Loss for epoch 35: 0.7132854263325806
Loss for epoch 36: 0.7105318561183155
Loss for epoch 37: 0.7080296428325882
Loss for epoch 38: 0.7057472165596762
Loss for epoch 39: 0.703658390713462

In [ ]:
with torch.no_grad():
    y_pred = model.forward(X_test)
    y_pred = (y_test_pred > 0.9).float()
    accuracy = (y_pred == y_test).float().mean()
    print(f"Accuracy: {accuracy.item()}")

RuntimeError: The size of tensor a (455) must match the size of tensor b (114) at non-singleton dimension 0