In [52]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

In [43]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [44]:
df.shape

(569, 33)

In [45]:
df = df.drop(columns=['id','Unnamed: 32'])

## Train, Test, Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [47]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
191,12.770,21.41,82.02,507.4,0.08749,0.06601,0.03112,0.028640,0.1694,0.06287,...,13.750,23.50,89.04,579.5,0.09388,0.08978,0.05186,0.04773,0.2179,0.06871
326,14.110,12.88,90.03,616.5,0.09309,0.05306,0.01765,0.027330,0.1373,0.05700,...,15.530,18.00,98.40,749.9,0.12810,0.11090,0.05307,0.05890,0.2100,0.07083
61,8.598,20.98,54.66,221.8,0.12430,0.08963,0.03000,0.009259,0.1828,0.06757,...,9.565,27.04,62.06,273.9,0.16390,0.16980,0.09001,0.02778,0.2972,0.07712
531,11.670,20.02,75.21,416.2,0.10160,0.09453,0.04200,0.021570,0.1859,0.06461,...,13.350,28.81,87.00,550.6,0.15500,0.29640,0.27580,0.08120,0.3206,0.08950
68,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.043750,0.2111,0.08046,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,25.730,17.46,174.20,2010.0,0.11490,0.23630,0.33680,0.191300,0.1956,0.06121,...,33.130,23.58,229.30,3234.0,0.15300,0.59370,0.64510,0.27560,0.3690,0.08815
413,14.990,22.11,97.53,693.7,0.08515,0.10250,0.06859,0.038760,0.1944,0.05913,...,16.760,31.55,110.20,867.1,0.10770,0.33450,0.31140,0.13080,0.3163,0.09251
301,12.460,19.89,80.43,471.3,0.08451,0.10140,0.06830,0.030990,0.1781,0.06249,...,13.460,23.07,88.13,551.3,0.10500,0.21580,0.19040,0.07625,0.2685,0.07764
460,17.080,27.15,111.20,930.9,0.09898,0.11100,0.10070,0.064310,0.1793,0.06281,...,22.960,34.49,152.10,1648.0,0.16000,0.24440,0.26390,0.15550,0.3010,0.09060
109,11.340,21.26,72.48,396.5,0.08759,0.06575,0.05133,0.018990,0.1487,0.06529,...,13.010,29.15,83.99,518.1,0.16990,0.21960,0.31200,0.08278,0.2829,0.08832

## Scaling

In [48]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
y_train

191    B
326    B
61     B
531    B
68     B
      ..
352    M
413    B
301    B
460    M
109    B
Name: diagnosis, Length: 455, dtype: str

## Label Encoding

In [50]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [51]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0])

## Numpy arrays to tensor

In [53]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [54]:
X_train.shape

torch.Size([455, 30])

In [56]:
X_train.shape[0]

455

In [55]:
X_train

tensor([[-0.4021,  0.4316, -0.4267,  ..., -1.0183, -1.1919, -0.8407],
        [-0.0329, -1.4816, -0.1073,  ..., -0.8526, -1.3207, -0.7259],
        [-1.5516,  0.3351, -1.5175,  ..., -1.3143,  0.1008, -0.3853],
        ...,
        [-0.4875,  0.0906, -0.4900,  ..., -0.5953, -0.3670, -0.3571],
        [ 0.7854,  1.7190,  0.7368,  ...,  0.5803,  0.1627,  0.3448],
        [-0.7961,  0.3979, -0.8070,  ..., -0.4984, -0.1323,  0.2213]],
       dtype=torch.float64)

## Main NN Class

In [69]:
class MySimpleNN:
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y_train * torch.log(y_pred) + (1-y_train) * torch.log(1-y_pred)).mean()
        return loss

## Important Parameters

In [57]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [72]:
# Create model
model = MySimpleNN(X=X_train)

# Define loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(X_train)


    # Loss Calculate
    loss = model.loss_function(y=y_train, y_pred=y_pred)
    print(f"Loss for epoch {epoch}: {loss}")

    # Backward Pass
    loss.backward()


    # Parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Clearing gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

Loss for epoch 0: 3.44253961146029
Loss for epoch 1: 3.306336380671811
Loss for epoch 2: 3.1666256108047506
Loss for epoch 3: 3.0209181928659095
Loss for epoch 4: 2.8694870868804307
Loss for epoch 5: 2.7121954667665613
Loss for epoch 6: 2.548177327605283
Loss for epoch 7: 2.3772434121571973
Loss for epoch 8: 2.2046386786680547
Loss for epoch 9: 2.036494974738592
Loss for epoch 10: 1.869689970251447
Loss for epoch 11: 1.708289668346328
Loss for epoch 12: 1.5554734037842775
Loss for epoch 13: 1.4111478951204512
Loss for epoch 14: 1.2779099322194813
Loss for epoch 15: 1.1611386699734552
Loss for epoch 16: 1.062267574062221
Loss for epoch 17: 0.9817705084837514
Loss for epoch 18: 0.9188972492856918
Loss for epoch 19: 0.8716702688926999
Loss for epoch 20: 0.8372099489999245
Loss for epoch 21: 0.8123454171423344
Loss for epoch 22: 0.7942396479596722
Loss for epoch 23: 0.7807198328582837
Loss for epoch 24: 0.7702820463068762